spring:
  application:
    name: musicbox

  datasource:
    url: jdbc:postgresql://localhost:5432/musicbox
    username: postgres
    password: gioele91@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  jwt-secret: MusicBoxPro_2026_Segreta_123456789_ABC
  jwt-expiration-ms: 86400000
  jamendo-client-id: "709fa152"
  discogs-token: ""
  discogs-user-agent: "MusicBoxPro/1.0 +mailto:giofriggia@gmail.com"
  cors-allowed-origins: "http://localhost:5173"
